Use gsed in mac
Sometime target files change empty by sed. The combination of cat, sed
and tee may be bad.

diff --git a/bin/setup b/bin/setup
--- a/bin/setup
+++ b/bin/setup
@@ -1,6 +1,16 @@
 #!/bin/bash
 
-set -x
+# set -x # debug
+
+if [ "$(uname)" == "Darwin" ]; then
+  command -v gsed >/dev/null 2>&1 || { echo >&2 "I require gsed but it's not installed. Execute 'brew install gnu-sed'. Aborting."; exit 1; }
+  SED=gsed
+elif [ "$(expr substr $(uname -s) 1 5)" == "Linux" ]; then
+  SED=sed
+else
+  echo Unknown OS
+  exit 1
+fi
 
 bin_dir=$(cd $(dirname $0) && pwd)
 root_dir=$bin_dir/..
@@ -9,16 +19,18 @@ git submodule update -i
 
 # setup frontend
 cd $root_dir/frontend
-cat src/agent.js | sed -e "s/'https.*\/api';/'http:\/\/localhost:3000\/api';/" | tee src/agent.js > /dev/null
+$SED -i -e "s/'https.*\/api';/'http:\/\/localhost:3000\/api';/" src/agent.js
 
 # setup frontend
 cd $root_dir/backend
-git grep -l 'ActiveRecord::Migration$' db/migrate | xargs -I"%" bash -c "cat % | sed -e 's/ActiveRecord::Migration$/ActiveRecord::Migration[4.2]/g' | tee %" > /dev/null
-cat Gemfile | sed -e "s/^gem 'devise',.*/gem 'devise'/" | tee Gemfile > /dev/null
-cat config/secrets.yml | sed -e "s/localhost:3000/localhost:4100/" | tee config/secrets.yml > /dev/null
+git grep -l 'ActiveRecord::Migration$' db/migrate | xargs -I"%" $SED -i -e 's/ActiveRecord::Migration$/ActiveRecord::Migration[4.2]/g' %
+$SED -i -e "s/^gem 'devise',.*/gem 'devise'/" Gemfile
+$SED -i -e "s/localhost:3000/localhost:4100/" config/secrets.yml
 
 cat <<EOF > config/initializers/devise_controller.rb
 Rails.application.config.to_prepare do
   DeviseController.respond_to :json
 end
 EOF
+
+echo "Complete!"
